### ISSUE TITLE
请问如何修改指令

### ISSUE THREAD

**Issue by tkosf** [yyx2684264/SeSeBot#1]
比如 【搜索艾薇】 增加多一条 【搜索av】 或者直接改成【搜索av】

**Comment by tkosf** [comment]
哈哈哈找到了  在lib目录下 但是请问如何增加指令呢

**Comment by yyx2684264** [comment]
> 
每个模块中有个Listen函数，在里面根据MsgData["message"]中的值添加if判断就行了
